export interface ViewUsersDetail {
    id?: string,
    name: string,
    email: string,
    address: string,
    phone_no: number | string,
    last_name?: string,
    bdate?: string,
    gender?: string,
    age?: number | string,
    city?: string,
    state?: string,
    pincode?: number | string,
    country?: string,
    father_name?: string,
    father_dob?: string,
    father_age?: number | string,
    mother_name?: string,
    mother_dob?: string,
    mother_age?: number | string,
    school_year?: number | string,
    school_name?: string,
    standard?: string,
    collage_year?: number | string,
    collage_name?: string,
    degree?: string,
    account_name?: string,
    account_type?: string,
    bank_name?: string,
    accoount_no?: number | string
    ifsc_code?: number | string,
    company_name?: string,
    company_address?: string,
    jooining_date?: string,
    salary?: number | string,
    adhar_card_url?: boolean,
    pan_card_url?: boolean,
    voting_card_url?: boolean,
    is_view?:boolean;
}