
import * as Yup from "yup";
export interface UsersDetail {
    id?: string,
    name: string,
    email: string,
    address: string,
    phone_no: number | string,
    last_name?: string,
    bdate?: string,
    gender?: string,
    age?: number | string,
    city?: string,
    state?: string,
    pincode?: number | string,
    country?: string,
    father_name?: string,
    father_dob?: string,
    father_age?: number | string,
    mother_name?: string,
    mother_dob?: string,
    mother_age?: number | string,
    school_year?: number | string,
    school_name?: string,
    standard?: string,
    collage_year?: number | string,
    collage_name?: string,
    degree?: string,
    account_name?: string,
    account_type?: string,
    bank_name?: string,
    accoount_no?: number | string
    ifsc_code?: number | string,
    company_name?: string,
    company_address?: string,
    jooining_date?: string,
    salary?: number | string,
    adhar_card_url?: string | null | boolean,
    pan_card_url?: string | null | boolean,
    voting_card_url?: string | null | boolean,
    is_view?:boolean;
}


export const EditSchema = Yup.object({
    name: Yup.string().min(4).max(20).matches(/^[A-Za-z\s]+$/, "Only characters are allowed").required("pelease  enter your name "),
    last_name: Yup.string().min(4).max(20).matches(/^[A-Za-z\s]+$/, "Only characters are allowed").required("pelease  enter your last name "),
    father_name: Yup.string().min(4).max(20).matches(/^[A-Za-z\s]+$/, "Only characters are allowed").required("pelease  enter your father name "),
    mother_name: Yup.string().min(4).max(20).matches(/^[A-Za-z\s]+$/, "Only characters are allowed").required("pelease enter your mother name "),
    school_name: Yup.string().min(4).max(20).matches(/^[A-Za-z\s]+$/, "Only characters are allowed").required("pelease enter your school name "),
    collage_name: Yup.string().min(4).max(20).matches(/^[A-Za-z\s]+$/, "Only characters are allowed").required("pelease enter your collage name "),
    account_name: Yup.string().min(4).max(20).matches(/^[A-Za-z\s]+$/, "Only characters are allowed").required("pelease enter your account name "),
    bank_name: Yup.string().min(4).max(20).matches(/^[A-Za-z\s]+$/, "Only characters are allowed").required("pelease enter your bank name "),
    company_name: Yup.string().min(4).max(20).matches(/^[A-Za-z\s]+$/, "Only characters are allowed").required("pelease enter your company name "),
    email: Yup.string().email().required("pelease entere your email"),
    address: Yup.string().required("pelease enter your address"),
    phone_no: Yup.string().matches(/^\d{10}$/, "Phone number must be exactly 10 digits").required("Please enter your phone number"),
    age: Yup.string().matches(/^\d{2}$/, " 2 digit only ").required("Please enter age"),
    father_age: Yup.string().matches(/^\d{2}$/, " 2 digit only").required("Please enter father age"),
    mother_age: Yup.string().matches(/^\d{2}$/, " 2 digit only ").required("Please enter mother age"),
    pincode: Yup.string().matches(/^\d{6}$/, "must be 6 digit ").required("Please enter pincode"),
    school_year: Yup.string().required("Please enter school year "),
    collage_year: Yup.string().required("Please enter collage year"),
    accoount_no: Yup.string().matches(/^\d{10}$/, " must be 10 degit ").required("Please enter account number"),
    ifsc_code: Yup.string().matches(/^\d{12}$/, " must be 12 degit ").required("Please enter ifsc code "),
    salary: Yup.string().required("Please enter salary"),
    adhar_card_url: Yup.string().url("Invalid URL").nullable(),
    pan_card_url: Yup.string().url("Invalid URL").nullable(),
    voting_card_url: Yup.string().url("Invalid URL").nullable(),
    company_address: Yup.string().nullable(),
    gender: Yup.string().oneOf(["male", "female"], "Invalid gender").nullable(),
    country: Yup.string().nullable(),
    city: Yup.string().nullable(),
    state: Yup.string().nullable(),
    account_type: Yup.string().nullable(),

});